# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import analytics_pb2 as gameclub_dot_v1_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOverview = channel.unary_unary(
                '/gameclub.analytics.v1.AnalyticsService/GetOverview',
                request_serializer=gameclub_dot_v1_dot_analytics__pb2.GetAnalyticsOverviewRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_analytics__pb2.AnalyticsOverview.FromString,
                _registered_method=True)
        self.GetClient = channel.unary_unary(
                '/gameclub.analytics.v1.AnalyticsService/GetClient',
                request_serializer=gameclub_dot_v1_dot_analytics__pb2.GetClientAnalyticsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_analytics__pb2.ClientAnalytics.FromString,
                _registered_method=True)


class AnalyticsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverview,
                    request_deserializer=gameclub_dot_v1_dot_analytics__pb2.GetAnalyticsOverviewRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_analytics__pb2.AnalyticsOverview.SerializeToString,
            ),
            'GetClient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClient,
                    request_deserializer=gameclub_dot_v1_dot_analytics__pb2.GetClientAnalyticsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_analytics__pb2.ClientAnalytics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.analytics.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.analytics.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.analytics.v1.AnalyticsService/GetOverview',
            gameclub_dot_v1_dot_analytics__pb2.GetAnalyticsOverviewRequest.SerializeToString,
            gameclub_dot_v1_dot_analytics__pb2.AnalyticsOverview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.analytics.v1.AnalyticsService/GetClient',
            gameclub_dot_v1_dot_analytics__pb2.GetClientAnalyticsRequest.SerializeToString,
            gameclub_dot_v1_dot_analytics__pb2.ClientAnalytics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
