# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import billing_pb2 as gameclub_dot_v1_dot_billing__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/billing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChargeSession = channel.unary_unary(
                '/gameclub.billing.v1.BillingService/ChargeSession',
                request_serializer=gameclub_dot_v1_dot_billing__pb2.ChargeSessionRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_billing__pb2.SessionCharge.FromString,
                _registered_method=True)
        self.GetSessionCharge = channel.unary_unary(
                '/gameclub.billing.v1.BillingService/GetSessionCharge',
                request_serializer=gameclub_dot_v1_dot_billing__pb2.GetSessionChargeRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_billing__pb2.SessionCharge.FromString,
                _registered_method=True)
        self.GetRevenue = channel.unary_unary(
                '/gameclub.billing.v1.BillingService/GetRevenue',
                request_serializer=gameclub_dot_v1_dot_billing__pb2.GetRevenueRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_billing__pb2.RevenueSummary.FromString,
                _registered_method=True)


class BillingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ChargeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionCharge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevenue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChargeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ChargeSession,
                    request_deserializer=gameclub_dot_v1_dot_billing__pb2.ChargeSessionRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_billing__pb2.SessionCharge.SerializeToString,
            ),
            'GetSessionCharge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionCharge,
                    request_deserializer=gameclub_dot_v1_dot_billing__pb2.GetSessionChargeRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_billing__pb2.SessionCharge.SerializeToString,
            ),
            'GetRevenue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevenue,
                    request_deserializer=gameclub_dot_v1_dot_billing__pb2.GetRevenueRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_billing__pb2.RevenueSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.billing.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.billing.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChargeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.billing.v1.BillingService/ChargeSession',
            gameclub_dot_v1_dot_billing__pb2.ChargeSessionRequest.SerializeToString,
            gameclub_dot_v1_dot_billing__pb2.SessionCharge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionCharge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.billing.v1.BillingService/GetSessionCharge',
            gameclub_dot_v1_dot_billing__pb2.GetSessionChargeRequest.SerializeToString,
            gameclub_dot_v1_dot_billing__pb2.SessionCharge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevenue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.billing.v1.BillingService/GetRevenue',
            gameclub_dot_v1_dot_billing__pb2.GetRevenueRequest.SerializeToString,
            gameclub_dot_v1_dot_billing__pb2.RevenueSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
