# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gameclub/v1/billing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'gameclub/v1/billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gameclub/v1/billing.proto\x12\x13gameclub.billing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x02\n\rSessionCharge\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x1c\n\x14\x62\x61lance_operation_id\x18\x04 \x01(\t\x12\x11\n\ttariff_id\x18\x05 \x01(\t\x12\x18\n\x10\x64uration_minutes\x18\x06 \x01(\x05\x12\x14\n\x0c\x61mount_cents\x18\x07 \x01(\x03\x12$\n\x1c\x61mount_before_discount_cents\x18\x08 \x01(\x03\x12\x1d\n\x15\x64iscount_amount_cents\x18\t \x01(\x03\x12\x1c\n\x14\x64iscount_percent_bps\x18\n \x01(\x05\x12\x19\n\x11\x64iscount_category\x18\x0b \x01(\t\x12\x12\n\ncharged_by\x18\x0c \x01(\t\x12\x17\n\x0fidempotency_key\x18\r \x01(\t\x12.\n\ncreated_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"C\n\x14\x43hargeSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\"-\n\x17GetSessionChargeRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"m\n\x11GetRevenueRequest\x12,\n\x08start_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06\x65nd_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x96\x01\n\x0eRevenueSummary\x12,\n\x08start_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06\x65nd_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x61mount_cents\x18\x03 \x01(\x03\x12\x14\n\x0c\x63harge_count\x18\x04 \x01(\x03\x32\xb1\x02\n\x0e\x42illingService\x12^\n\rChargeSession\x12).gameclub.billing.v1.ChargeSessionRequest\x1a\".gameclub.billing.v1.SessionCharge\x12\x64\n\x10GetSessionCharge\x12,.gameclub.billing.v1.GetSessionChargeRequest\x1a\".gameclub.billing.v1.SessionCharge\x12Y\n\nGetRevenue\x12&.gameclub.billing.v1.GetRevenueRequest\x1a#.gameclub.billing.v1.RevenueSummaryB\'\xaa\x02$GameClub.Client.Contracts.Billing.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gameclub.v1.billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002$GameClub.Client.Contracts.Billing.V1'
  _globals['_SESSIONCHARGE']._serialized_start=84
  _globals['_SESSIONCHARGE']._serialized_end=466
  _globals['_CHARGESESSIONREQUEST']._serialized_start=468
  _globals['_CHARGESESSIONREQUEST']._serialized_end=535
  _globals['_GETSESSIONCHARGEREQUEST']._serialized_start=537
  _globals['_GETSESSIONCHARGEREQUEST']._serialized_end=582
  _globals['_GETREVENUEREQUEST']._serialized_start=584
  _globals['_GETREVENUEREQUEST']._serialized_end=693
  _globals['_REVENUESUMMARY']._serialized_start=696
  _globals['_REVENUESUMMARY']._serialized_end=846
  _globals['_BILLINGSERVICE']._serialized_start=849
  _globals['_BILLINGSERVICE']._serialized_end=1154
# @@protoc_insertion_point(module_scope)
