# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import cash_shifts_pb2 as gameclub_dot_v1_dot_cash__shifts__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/cash_shifts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CashShiftServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/Open',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.OpenCashShiftRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/Get',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.GetCashShiftRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/List',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashShiftsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashShiftsResponse.FromString,
                _registered_method=True)
        self.ListMovements = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/ListMovements',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashMovementsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashMovementsResponse.FromString,
                _registered_method=True)
        self.RecordMovement = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/RecordMovement',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.RecordCashMovementRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashMovement.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/Close',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CloseCashShiftRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.FromString,
                _registered_method=True)
        self.Approve = channel.unary_unary(
                '/gameclub.cash_shifts.v1.CashShiftService/Approve',
                request_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CreateCashApprovalRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashApproval.FromString,
                _registered_method=True)


class CashShiftServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMovements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordMovement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Approve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CashShiftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.OpenCashShiftRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.GetCashShiftRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashShiftsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashShiftsResponse.SerializeToString,
            ),
            'ListMovements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMovements,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashMovementsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.ListCashMovementsResponse.SerializeToString,
            ),
            'RecordMovement': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordMovement,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.RecordCashMovementRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashMovement.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CloseCashShiftRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.SerializeToString,
            ),
            'Approve': grpc.unary_unary_rpc_method_handler(
                    servicer.Approve,
                    request_deserializer=gameclub_dot_v1_dot_cash__shifts__pb2.CreateCashApprovalRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_cash__shifts__pb2.CashApproval.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.cash_shifts.v1.CashShiftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.cash_shifts.v1.CashShiftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CashShiftService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/Open',
            gameclub_dot_v1_dot_cash__shifts__pb2.OpenCashShiftRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/Get',
            gameclub_dot_v1_dot_cash__shifts__pb2.GetCashShiftRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/List',
            gameclub_dot_v1_dot_cash__shifts__pb2.ListCashShiftsRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.ListCashShiftsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMovements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/ListMovements',
            gameclub_dot_v1_dot_cash__shifts__pb2.ListCashMovementsRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.ListCashMovementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordMovement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/RecordMovement',
            gameclub_dot_v1_dot_cash__shifts__pb2.RecordCashMovementRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.CashMovement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/Close',
            gameclub_dot_v1_dot_cash__shifts__pb2.CloseCashShiftRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.CashShift.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Approve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.cash_shifts.v1.CashShiftService/Approve',
            gameclub_dot_v1_dot_cash__shifts__pb2.CreateCashApprovalRequest.SerializeToString,
            gameclub_dot_v1_dot_cash__shifts__pb2.CashApproval.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
