# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import catalog_pb2 as gameclub_dot_v1_dot_catalog__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProduct = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/CreateProduct',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.Product.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/ListProducts',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.CreateTariff = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/CreateTariff',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.CreateTariffRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.Tariff.FromString,
                _registered_method=True)
        self.ListTariffs = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/ListTariffs',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.ListTariffsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.ListTariffsResponse.FromString,
                _registered_method=True)
        self.PublishTariff = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/PublishTariff',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.PublishTariffRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.Tariff.FromString,
                _registered_method=True)
        self.ArchiveTariff = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/ArchiveTariff',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.ArchiveTariffRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.Tariff.FromString,
                _registered_method=True)
        self.CreateDiscountRule = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/CreateDiscountRule',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.CreateDiscountRuleRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.DiscountRule.FromString,
                _registered_method=True)
        self.ListDiscountRules = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/ListDiscountRules',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.ListDiscountRulesRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.ListDiscountRulesResponse.FromString,
                _registered_method=True)
        self.GetCatalogSnapshot = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/GetCatalogSnapshot',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.GetCatalogSnapshotRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.CatalogSnapshot.FromString,
                _registered_method=True)
        self.Quote = channel.unary_unary(
                '/gameclub.catalog.v1.CatalogService/Quote',
                request_serializer=gameclub_dot_v1_dot_catalog__pb2.QuoteRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_catalog__pb2.QuoteResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTariff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTariffs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTariff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveTariff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDiscountRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDiscountRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCatalogSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Quote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.CreateProductRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.Product.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.ListProductsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.ListProductsResponse.SerializeToString,
            ),
            'CreateTariff': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTariff,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.CreateTariffRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.Tariff.SerializeToString,
            ),
            'ListTariffs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTariffs,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.ListTariffsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.ListTariffsResponse.SerializeToString,
            ),
            'PublishTariff': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTariff,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.PublishTariffRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.Tariff.SerializeToString,
            ),
            'ArchiveTariff': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveTariff,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.ArchiveTariffRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.Tariff.SerializeToString,
            ),
            'CreateDiscountRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDiscountRule,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.CreateDiscountRuleRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.DiscountRule.SerializeToString,
            ),
            'ListDiscountRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDiscountRules,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.ListDiscountRulesRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.ListDiscountRulesResponse.SerializeToString,
            ),
            'GetCatalogSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalogSnapshot,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.GetCatalogSnapshotRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.CatalogSnapshot.SerializeToString,
            ),
            'Quote': grpc.unary_unary_rpc_method_handler(
                    servicer.Quote,
                    request_deserializer=gameclub_dot_v1_dot_catalog__pb2.QuoteRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_catalog__pb2.QuoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.catalog.v1.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.catalog.v1.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/CreateProduct',
            gameclub_dot_v1_dot_catalog__pb2.CreateProductRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/ListProducts',
            gameclub_dot_v1_dot_catalog__pb2.ListProductsRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTariff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/CreateTariff',
            gameclub_dot_v1_dot_catalog__pb2.CreateTariffRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.Tariff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTariffs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/ListTariffs',
            gameclub_dot_v1_dot_catalog__pb2.ListTariffsRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.ListTariffsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTariff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/PublishTariff',
            gameclub_dot_v1_dot_catalog__pb2.PublishTariffRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.Tariff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveTariff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/ArchiveTariff',
            gameclub_dot_v1_dot_catalog__pb2.ArchiveTariffRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.Tariff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDiscountRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/CreateDiscountRule',
            gameclub_dot_v1_dot_catalog__pb2.CreateDiscountRuleRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.DiscountRule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDiscountRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/ListDiscountRules',
            gameclub_dot_v1_dot_catalog__pb2.ListDiscountRulesRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.ListDiscountRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCatalogSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/GetCatalogSnapshot',
            gameclub_dot_v1_dot_catalog__pb2.GetCatalogSnapshotRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.CatalogSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Quote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.catalog.v1.CatalogService/Quote',
            gameclub_dot_v1_dot_catalog__pb2.QuoteRequest.SerializeToString,
            gameclub_dot_v1_dot_catalog__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
