# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import clients_pb2 as gameclub_dot_v1_dot_clients__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/clients_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/Create',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.CreateClientRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.Client.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/Search',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.SearchClientsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.SearchClientsResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/Get',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.GetClientRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.Client.FromString,
                _registered_method=True)
        self.TopUp = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/TopUp',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.TopUpRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.TopUpResponse.FromString,
                _registered_method=True)
        self.ListBalanceOperations = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/ListBalanceOperations',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.ListBalanceOperationsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.ListBalanceOperationsResponse.FromString,
                _registered_method=True)
        self.CreateGuest = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/CreateGuest',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.CreateGuestRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.Guest.FromString,
                _registered_method=True)
        self.SearchGuests = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/SearchGuests',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.SearchGuestsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.SearchGuestsResponse.FromString,
                _registered_method=True)
        self.GetGuest = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/GetGuest',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.GetGuestRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.Guest.FromString,
                _registered_method=True)
        self.ListGuests = channel.unary_unary(
                '/gameclub.clients.v1.ClientService/ListGuests',
                request_serializer=gameclub_dot_v1_dot_clients__pb2.ListGuestsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_clients__pb2.ListGuestsResponse.FromString,
                _registered_method=True)


class ClientServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBalanceOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGuest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGuests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGuest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGuests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.CreateClientRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.Client.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.SearchClientsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.SearchClientsResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.GetClientRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.Client.SerializeToString,
            ),
            'TopUp': grpc.unary_unary_rpc_method_handler(
                    servicer.TopUp,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.TopUpRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.TopUpResponse.SerializeToString,
            ),
            'ListBalanceOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBalanceOperations,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.ListBalanceOperationsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.ListBalanceOperationsResponse.SerializeToString,
            ),
            'CreateGuest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGuest,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.CreateGuestRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.Guest.SerializeToString,
            ),
            'SearchGuests': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGuests,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.SearchGuestsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.SearchGuestsResponse.SerializeToString,
            ),
            'GetGuest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGuest,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.GetGuestRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.Guest.SerializeToString,
            ),
            'ListGuests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGuests,
                    request_deserializer=gameclub_dot_v1_dot_clients__pb2.ListGuestsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_clients__pb2.ListGuestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.clients.v1.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.clients.v1.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/Create',
            gameclub_dot_v1_dot_clients__pb2.CreateClientRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.Client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/Search',
            gameclub_dot_v1_dot_clients__pb2.SearchClientsRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.SearchClientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/Get',
            gameclub_dot_v1_dot_clients__pb2.GetClientRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.Client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TopUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/TopUp',
            gameclub_dot_v1_dot_clients__pb2.TopUpRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.TopUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBalanceOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/ListBalanceOperations',
            gameclub_dot_v1_dot_clients__pb2.ListBalanceOperationsRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.ListBalanceOperationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGuest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/CreateGuest',
            gameclub_dot_v1_dot_clients__pb2.CreateGuestRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.Guest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchGuests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/SearchGuests',
            gameclub_dot_v1_dot_clients__pb2.SearchGuestsRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.SearchGuestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGuest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/GetGuest',
            gameclub_dot_v1_dot_clients__pb2.GetGuestRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.Guest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGuests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.clients.v1.ClientService/ListGuests',
            gameclub_dot_v1_dot_clients__pb2.ListGuestsRequest.SerializeToString,
            gameclub_dot_v1_dot_clients__pb2.ListGuestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
