# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import reservations_pb2 as gameclub_dot_v1_dot_reservations__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/reservations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReservationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAvailability = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/CheckAvailability',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/Create',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.CreateReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/List',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.ListReservationsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.ListReservationsResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/Get',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/Update',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.UpdateReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/Cancel',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.CancelReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)
        self.Activate = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/Activate',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.ActivateReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/Complete',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.CompleteReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)
        self.MarkNoShow = channel.unary_unary(
                '/gameclub.reservations.v1.ReservationService/MarkNoShow',
                request_serializer=gameclub_dot_v1_dot_reservations__pb2.MarkNoShowReservationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
                _registered_method=True)


class ReservationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Activate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkNoShow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.CreateReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.ListReservationsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.ListReservationsResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.GetReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.UpdateReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.CancelReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.ActivateReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.CompleteReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
            'MarkNoShow': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkNoShow,
                    request_deserializer=gameclub_dot_v1_dot_reservations__pb2.MarkNoShowReservationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_reservations__pb2.Reservation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.reservations.v1.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.reservations.v1.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/CheckAvailability',
            gameclub_dot_v1_dot_reservations__pb2.CheckAvailabilityRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/Create',
            gameclub_dot_v1_dot_reservations__pb2.CreateReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/List',
            gameclub_dot_v1_dot_reservations__pb2.ListReservationsRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.ListReservationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/Get',
            gameclub_dot_v1_dot_reservations__pb2.GetReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/Update',
            gameclub_dot_v1_dot_reservations__pb2.UpdateReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/Cancel',
            gameclub_dot_v1_dot_reservations__pb2.CancelReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/Activate',
            gameclub_dot_v1_dot_reservations__pb2.ActivateReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/Complete',
            gameclub_dot_v1_dot_reservations__pb2.CompleteReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkNoShow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.reservations.v1.ReservationService/MarkNoShow',
            gameclub_dot_v1_dot_reservations__pb2.MarkNoShowReservationRequest.SerializeToString,
            gameclub_dot_v1_dot_reservations__pb2.Reservation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
