# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import sessions_pb2 as gameclub_dot_v1_dot_sessions__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/sessions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/gameclub.sessions.v1.SessionService/Start',
                request_serializer=gameclub_dot_v1_dot_sessions__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_sessions__pb2.Session.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gameclub.sessions.v1.SessionService/Get',
                request_serializer=gameclub_dot_v1_dot_sessions__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_sessions__pb2.Session.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/gameclub.sessions.v1.SessionService/List',
                request_serializer=gameclub_dot_v1_dot_sessions__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_sessions__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/gameclub.sessions.v1.SessionService/Stop',
                request_serializer=gameclub_dot_v1_dot_sessions__pb2.StopSessionRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_sessions__pb2.Session.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=gameclub_dot_v1_dot_sessions__pb2.StartSessionRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_sessions__pb2.Session.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=gameclub_dot_v1_dot_sessions__pb2.GetSessionRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_sessions__pb2.Session.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gameclub_dot_v1_dot_sessions__pb2.ListSessionsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_sessions__pb2.ListSessionsResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=gameclub_dot_v1_dot_sessions__pb2.StopSessionRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_sessions__pb2.Session.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.sessions.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.sessions.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.sessions.v1.SessionService/Start',
            gameclub_dot_v1_dot_sessions__pb2.StartSessionRequest.SerializeToString,
            gameclub_dot_v1_dot_sessions__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.sessions.v1.SessionService/Get',
            gameclub_dot_v1_dot_sessions__pb2.GetSessionRequest.SerializeToString,
            gameclub_dot_v1_dot_sessions__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.sessions.v1.SessionService/List',
            gameclub_dot_v1_dot_sessions__pb2.ListSessionsRequest.SerializeToString,
            gameclub_dot_v1_dot_sessions__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.sessions.v1.SessionService/Stop',
            gameclub_dot_v1_dot_sessions__pb2.StopSessionRequest.SerializeToString,
            gameclub_dot_v1_dot_sessions__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
