# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gameclub/v1/system.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'gameclub/v1/system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18gameclub/v1/system.proto\x12\x12gameclub.system.v1\"\x0f\n\rHealthRequest\"B\n\x0eHealthResponse\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2c\n\rSystemService\x12R\n\tGetHealth\x12!.gameclub.system.v1.HealthRequest\x1a\".gameclub.system.v1.HealthResponseB\x1eP\x01\xaa\x02\x19GameClub.Client.Contractsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gameclub.v1.system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\252\002\031GameClub.Client.Contracts'
  _globals['_HEALTHREQUEST']._serialized_start=48
  _globals['_HEALTHREQUEST']._serialized_end=63
  _globals['_HEALTHRESPONSE']._serialized_start=65
  _globals['_HEALTHRESPONSE']._serialized_end=131
  _globals['_SYSTEMSERVICE']._serialized_start=133
  _globals['_SYSTEMSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
