# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gameclub.v1 import workstations_pb2 as gameclub_dot_v1_dot_workstations__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gameclub/v1/workstations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkstationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/Register',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.RegisterWorkstationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.Workstation.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/Heartbeat',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.Workstation.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/List',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationsResponse.FromString,
                _registered_method=True)
        self.Disable = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/Disable',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.DisableWorkstationRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.Workstation.FromString,
                _registered_method=True)
        self.DispatchCommand = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/DispatchCommand',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.DispatchCommandRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.FromString,
                _registered_method=True)
        self.WatchCommands = channel.unary_stream(
                '/gameclub.workstations.v1.WorkstationService/WatchCommands',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.WatchCommandsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.FromString,
                _registered_method=True)
        self.AcknowledgeCommand = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/AcknowledgeCommand',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.AcknowledgeCommandRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.FromString,
                _registered_method=True)
        self.ListGroups = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/ListGroups',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationGroupsRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationGroupsResponse.FromString,
                _registered_method=True)
        self.UpsertGroup = channel.unary_unary(
                '/gameclub.workstations.v1.WorkstationService/UpsertGroup',
                request_serializer=gameclub_dot_v1_dot_workstations__pb2.UpsertWorkstationGroupRequest.SerializeToString,
                response_deserializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationGroup.FromString,
                _registered_method=True)


class WorkstationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkstationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.RegisterWorkstationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.Workstation.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.HeartbeatRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.Workstation.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationsResponse.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.DisableWorkstationRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.Workstation.SerializeToString,
            ),
            'DispatchCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchCommand,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.DispatchCommandRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.SerializeToString,
            ),
            'WatchCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchCommands,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.WatchCommandsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.SerializeToString,
            ),
            'AcknowledgeCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeCommand,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.AcknowledgeCommandRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.SerializeToString,
            ),
            'ListGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroups,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationGroupsRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.ListWorkstationGroupsResponse.SerializeToString,
            ),
            'UpsertGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertGroup,
                    request_deserializer=gameclub_dot_v1_dot_workstations__pb2.UpsertWorkstationGroupRequest.FromString,
                    response_serializer=gameclub_dot_v1_dot_workstations__pb2.WorkstationGroup.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gameclub.workstations.v1.WorkstationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gameclub.workstations.v1.WorkstationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkstationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/Register',
            gameclub_dot_v1_dot_workstations__pb2.RegisterWorkstationRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.Workstation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/Heartbeat',
            gameclub_dot_v1_dot_workstations__pb2.HeartbeatRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.Workstation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/List',
            gameclub_dot_v1_dot_workstations__pb2.ListWorkstationsRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.ListWorkstationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/Disable',
            gameclub_dot_v1_dot_workstations__pb2.DisableWorkstationRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.Workstation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/DispatchCommand',
            gameclub_dot_v1_dot_workstations__pb2.DispatchCommandRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/WatchCommands',
            gameclub_dot_v1_dot_workstations__pb2.WatchCommandsRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/AcknowledgeCommand',
            gameclub_dot_v1_dot_workstations__pb2.AcknowledgeCommandRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.WorkstationCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/ListGroups',
            gameclub_dot_v1_dot_workstations__pb2.ListWorkstationGroupsRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.ListWorkstationGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gameclub.workstations.v1.WorkstationService/UpsertGroup',
            gameclub_dot_v1_dot_workstations__pb2.UpsertWorkstationGroupRequest.SerializeToString,
            gameclub_dot_v1_dot_workstations__pb2.WorkstationGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
