<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>HubShellSteam</AssemblyName>
    <Product>HubShell Steam Guest</Product>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HubShell.SteamGuest.Core\HubShell.SteamGuest.Core.csproj" />
  </ItemGroup>
</Project>
